CREATE TABLE BUS (
    CUST_NUMB CHAR(9),
    CUST_TYPE CHAR(1),
    NATNID_REGNNUMB CHAR(20),
    CUST_TITL_LINE1 CHAR(34),
    DSCT_DESC_L CHAR(27),
    BIRTHDAY CHAR(8),
    BRANCH CHAR(4),
    DATE_ESTB CHAR(10),
    CUST_STAT CHAR(3),
    BIZ_TYPE CHAR(6),
    CUST_ASSNNATID CHAR(10),
    CUST_ASSNNAME CHAR(34)
);

CREATE TABLE LUS (
    ACCT_NO VARCHAR(14),
    UNINO VARCHAR(11),
    PROD_NAME VARCHAR(4),
    BALANCE DECIMAL(13,2),
    INTEREST DECIMAL(7,5),
    STATUS VARCHAR(10),
    NAME NVARCHAR(100),
    NEW_B_CODE VARCHAR(6),
    PERSON_TYPE VARCHAR(1),
    COMPANY VARCHAR(3),
    COMM_ADR NVARCHAR(100),
    BRANCH_CODE VARCHAR(3),
    BRANCH_NAME VARCHAR(50),
    CURR_CODE VARCHAR(4),
    LCB_ACCOUNT CHAR(1),
    B_CODE VARCHAR(6),
    LEGAL_ADR NVARCHAR(100),
    TEL_NO_1 VARCHAR(20),
    TEL_NO_2 VARCHAR(20),
    OBU_DBU VARCHAR(3)
);

CREATE TABLE SEC_USRBASIC (
    USR_ID_C VARCHAR(10) NOT NULL,
    USR_NAME_C VARCHAR(30) NOT NULL,
    MKR_DATE_C CHAR(8) NOT NULL,
    EXP_DATE_C CHAR(8) NOT NULL,
    LST_CHND_C CHAR(8) NULL,
    LST_CHNT_C CHAR(8) NULL,
    LST_USED_C CHAR(8) NULL,
    LST_USET_C CHAR(8) NULL,
    USR_STAT_S CHAR(1) NOT NULL,
    ERR_CNT_N TINYINT NOT NULL,
    DEP_ID_C VARCHAR(10) NOT NULL,
    MKR_ID_C VARCHAR(10) NOT NULL,
    APR_ID_C VARCHAR(10) NULL,
    APR_DATE_C CHAR(8) NULL,
    EFF_BGN_C CHAR(8) NULL,
    EFF_END_C CHAR(8) NULL,
    MNU_ID_C VARCHAR(10) NULL,
    EXT_CODE_C VARCHAR(10) NULL,
    MNU_CHNG_F CHAR(1) NULL,
    USR_PWD_C BINARY(32) NOT NULL CONSTRAINT DF__sec_usrba__usr_p__6B24EA82  DEFAULT (0x01),
    USR_PWD1_C BINARY(32) NULL,
    USR_PWD2_C BINARY(32) NULL,
    USR_PWD3_C BINARY(32) NULL,
    USR_PWD4_C BINARY(32) NULL,
    USR_PWD5_C BINARY(32) NULL,
    USR_PWD6_C BINARY(32) NULL,
    LAST_NAME_C VARCHAR(30) NULL,
    FIRST_NAME_C VARCHAR(20) NULL,
    GEID_ID_N NUMERIC(10, 0) NULL
);

CREATE TABLE SEC_USRGROUP (
    USR_ID_C VARCHAR(10) NOT NULL,
    GRP_ID_C VARCHAR(10) NOT NULL
);

CREATE TABLE SEC_MENU (
    FUNCTIONID VARCHAR(10) NOT NULL,
    SUBMENU VARCHAR(60) NULL,
    ITEMSEQ NUMERIC(6, 3) NULL,
    FORMNAME VARCHAR(30) NULL,
    TXCODE VARCHAR(10) NULL,
    UPDATEDATE DATETIME NULL,
    UPDATEUSER VARCHAR(10) NULL,
    CONSTRAINT PK_SEC_MENU PRIMARY KEY CLUSTERED (FUNCTIONID ASC) WITH (IGNORE_DUP_KEY = OFF)
);

CREATE TABLE SEC_FUNBASIC (
    FUN_ID_C VARCHAR(10) NOT NULL,
    FUN_NAME_C VARCHAR(60) NOT NULL,
    SYS_ID_C CHAR(4) NOT NULL,
    ADD_RGHT_F CHAR(1) NULL,
    CHA_RGHT_F CHAR(1) NULL,
    DEL_RGHT_F CHAR(1) NULL,
    INQ_RGHT_F CHAR(1) NULL,
    EXE_RGHT_F CHAR(1) NULL,
    PRI_RGHT_F CHAR(1) NULL
);

CREATE TABLE SEC_GRPBASIC (
    GRP_ID_C VARCHAR(10) NOT NULL,
    GRP_NAME_C VARCHAR(60) NOT NULL,
    SYS_ID_C CHAR(4) NOT NULL
);

CREATE TABLE SEC_GRPRIGHT (
    GRP_ID_C VARCHAR(10) NOT NULL,
    FUN_ID_C VARCHAR(10) NOT NULL,
    ADD_RGHT_F CHAR(1) NOT NULL,
    CHA_RGHT_F CHAR(1) NOT NULL,
    DEL_RGHT_F CHAR(1) NOT NULL,
    INQ_RGHT_F CHAR(1) NOT NULL,
    EXE_RGHT_F CHAR(1) NOT NULL,
    PRI_RGHT_F CHAR(1) NOT NULL
);

CREATE TABLE SEC_SYSBASIC (
    SYS_ID_C CHAR(4) NOT NULL,
    SYS_NAME_C VARCHAR(60) NOT NULL,
    SYS_CODE_C VARCHAR(3) NOT NULL,
    EXE_PATH_C VARCHAR(120) NOT NULL,
    PRI_PATH_C VARCHAR(120) NULL,
    ADD_CMD_ARG VARCHAR(20) NULL
);
